controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\TrickController::index

get_trick:
    path: /trick/{slug}
    controller: App\Controller\TrickController::getTrick

login:
    path: /login
    controller: App\Controller\LoginController::index

registration:
    path: /register
    controller: App\Controller\RegistrationController::index

forgot_password:
    path: /forgot_password
    controller: App\Controller\LoginController::forgetPassword

reset_password:
    path: /reset_password/token
    controller: App\Controller\LoginController::resetPassword